version: '3'

services:
  proxy:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    expose:
      - 3000
    depends_on:
      - db
  db:
    build: 
      context: mysql
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      - node-network
      
networks:
  node-network:
    driver: bridge